export const projectData = [
  {
    title: 'ELMS',
    banner: [
      'https://res.cloudinary.com/dfhhkd04c/image/upload/v1753859077/els-1_eiecqj.png',
      'https://res.cloudinary.com/dfhhkd04c/image/upload/v1753855124/els-2_vkx4vf.png',
    ],
    web_link: 'https://e-learning-two-opal.vercel.app/',
    stack: ['MongoDB', 'Express', 'React', 'Node.js', 'Tailwind CSS'],
    description:
      'A full-featured E-commerce and Event Learning Management System focused on selling educational event-related products and managing student engagement, with integrated payment solutions.',
    features: [
      'Module creation and management',
      'Interactive quizzes and assessments',
      'Automatic quiz scoring and feedback',
      'Student profile and progress tracking',
      'Role-based access (admin, instructor, student)',
      'Secure payment integration for course/event purchases',
      'Event scheduling and calendar system',
      'Admin dashboard with analytics',
    ],
    type: 'Web Development',
    testAccount: ['2', '1'],
    github: 'https://github.com/Alex-Xandre/els.git',
  },

  {
    title: 'Membo',
    banner: ['https://res.cloudinary.com/dnhka2l80/image/upload/v1742269695/membo_zbz5be.png'],
    web_link: 'https://membo-nine.vercel.app/',
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS'],
    description: 'E-commerce Website that focus mainly on Event management system products with payment integrations.',
    features: [],
    type: 'Web Development',
    github: 'https://github.com/Alex-Xandre/membo',
  },

  {
    title: 'Anywear Fashion',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1744296663/anywear_vsoky7.png'],
    web_link: 'https://www.anywear-fashion-trading.com/',
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS', 'React Native'],
    description: 'HR Management System that handles HR related task and progress quotas',
    features: [],
    type: 'Web Development Mobile Application',
  },

  {
    title: 'Planteria',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1700539674/proj_1_fttl7o.png'],
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS'],
    description: 'E-commerce Website that focus mainly on plant products with payment integrations.',
    web_link: 'https://bukal-garden-planteria.store/',
    type: 'Web Development',
    imageSlideShow: [],
    features: [
      'Developed a full functional ecommerce app exclusively for Plant Selling using React on frontend and Node JS with express on backend.',
      'Implemented an inventory system and payment Integrations',
      'Created a separate module for seller, admin, and user',
    ],
    testAccount: ['xndrmcua22@gmail.com', '12345678'],
  },

  {
    title: 'DineEase',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1690989227/proj-3-removebg-preview_yrzyse_1_iytqvm.png'],
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS'],
    description: 'A Restaurant Management System for a Samgyupsal Business.',
    web_link: 'https://dineease-8pbh.onrender.com/',
    type: 'Web Development',
    testAccount: ['T1', 'customer'],
    features: [
      'Developed a full functional restaurant app exclusively for Samgyupsal Business using React on frontend and Node JS with express on backend.',
      'Implemented an inventory system, payment Integrations and realtime-ordering',
      'Created a separate module for Admin, Customers, Kitchen and Cashier',
    ],
  },

  {
    title: 'Yes-O Calaca',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1700542829/proj2_rnhyco.png'],
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS'],
    description: 'Volunteer Management System of Youth for Environment in Schools.',
    web_link: 'https://www.yes-o-calaca-shs.com/',
    type: 'Web Development',
    features: [
      'Developed a full functional Volunteer Management System using React on frontend and Node JS with express on backend.',
      'Implemented a social-media style platform and donation features',
      'Created a separate module for admin and volunteer users.',
    ],
    testAccount: ['xndrmcua22@gmail.com', '12345678'],
  },

  {
    title: 'MTP-Educational As',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1700539674/proj_1_fttl7o.png'],
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS'],
    description: 'Automated Scholarship Application System with Chat Feature.',
    web_link: 'https://www.mtp-educational-assistance.com/',
    type: 'Web Development',
    testAccount: ['xndrmcua22@gmail.com', '12345678'],
    features: [
      ' Developed a full functional scholarship assessment website with chat features using React on frontend and Node JS with express on backend.',
      'Added a chat feature using sockets',
      'Created a separate module for admin and applicant',
    ],
  },
  {
    title: 'As Glass Aluminum',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1691459923/OT12YY1_wgu70c.png'],
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Styled Components'],
    description: 'A Ecommerce for a Glass and Aluminum Business on the Philipines',
    web_link: 'https://glass-aluminum.onrender.com/',
    type: 'Web Development',
    testAccount: ['xndrmcua22@gmail.com', 'xndrmcua22@gmail.com'],
    features: [
      'Developed a full functional ecommerce app exclusively for Hardware Business using React on frontend and Node JS with express on backend.',
      'Implemented an inventory system, payment Integrations and booking of services',
      'Created a separate module for Admin and Customer',
    ],
  },
  {
    title: 'IRemember',
    banner: ['https://res.cloudinary.com/dfhhkd04c/image/upload/v1703333491/OWINKS1_zhzgcg.png'],
    stack: ['MongoDB', 'Express', 'React', 'Node JS', 'Tailwind CSS'],
    description: 'An End-of-Life Planner and Online Pet Memorial System for Pet Owners.',
    web_link: 'https://www.ipetmemorial-iremember.com/',
    type: 'Web Development',
    testAccount: ['starlight1', 'starlight1'],
    features: [
      'Developed a full functional social media app exclusively for pet owners which focuses on pet memorials and veterinarian clinic services.',
      'Implemented booking of services, blog features, and email notifications.',
      ' Created a separate module for admin, service provider and pet owners.',
    ],
  },
];
